# kubectl label nodes aks-nodepool1-33326899-0 disktype=ssd
# kubectl label nodes aks-nodepool1-33326899-1 disktype=ssd

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nepetersv2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nepetersv1
  template:
    metadata:
      labels:
        app: nepetersv1
    spec:
      containers:
      - name: nepetersv1
        image: neilpeterson/nepetersv1
      nodeSelector:
          disktype: ssd