# kubectl taint nodes aks-nodepool1-19214297-2 dept=it:NoSchedule

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nepetersv1-non-tollerated
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nepetersv1-non-tollerated
  template:
    metadata:
      labels:
        app: nepetersv1-non-tollerated
    spec:
      containers:
      - name: nepetersv1-non-tollerated
        image: neilpeterson/nepetersv1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nepetersv1-tollerated
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nepetersv1-tollerated
  template:
    metadata:
      labels:
        app: nepetersv1-tollerated
    spec:
      containers:
      - name: nepetersv1-tollerated
        image: neilpeterson/nepetersv1
      tolerations:
      - key: dept
        value: it
